### ISSUE TITLE
Wondering about MS-processing tools that can use MZTree format

### ISSUE THREAD

**Issue by lfnothias** [optimusmoose/MZTree#1]
Hi,
I am just wondering if there is already some MS-processing tools that can use MZTree format ?
Thank you

**Comment by optimusmoose** [comment]
Hi,
MZTree is not a format like, say, mzML or .raw. It is a storage and
retrieval system.

To date, the only public project I am aware of that uses MZTree is JS-MS:
https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-017-1883-6

We have an expanded version of both projects that is being commercially
developed via Prime Labs (www.primelabs.ms) and if you are interested, we
can consider whether you'd make a good beta tester.

Thanks,
Rob

**Comment by lfnothias** [comment]
Thanks. Awesome !
